import 'dotenv/config'; import slugify from 'slugify'; import db from './db.js'; import { hashPasswordSync, verifyPasswordSync, assessPassword, MIN_LENGTH } from './password.js';
const services=[
['Manuscript Editing','Developmental and line editing that strengthens structure, clarity, voice and reader impact.','We review your manuscript as a complete work, then provide precise editorial guidance and tracked improvements.',['Clearer structure','Consistent voice','Professional language'],['Editorial assessment','Editing plan','Tracked editing','Author review'],['Edited manuscript','Editorial report','Style sheet']],
['Proofreading','A meticulous final language and production check before release.','Our proofreaders correct grammar, spelling, punctuation, consistency and layout errors before publication.',['Publication confidence','Fewer costly reprints','Clean reader experience'],['File review','Proofread','Quality check','Final corrections'],['Marked proof','Clean final file']],
['Book Publishing','End-to-end support from manuscript assessment to a professionally produced book.','A coordinated publishing pathway covering editorial, design, production guidance and launch readiness.',['One accountable partner','Quality-controlled workflow','Author support'],['Assessment','Editorial','Design','Proofing','Production'],['Print-ready files','Digital edition','Publishing guidance']],
['Book Layout & Formatting','Reader-friendly interior design for print and digital editions.','Professional typography, page architecture and export standards suitable for printers and digital platforms.',['Readable pages','Consistent styling','Printer-ready output'],['Content cleanup','Design sample','Full layout','Corrections','Export'],['Print PDF','Editable source','EPUB-ready file']],
['Book Cover Design','Original covers that communicate genre, value and credibility.','We translate the book promise into a distinctive cover system for print and digital channels.',['Stronger first impression','Market-fit design','Complete print wrap'],['Creative brief','Concepts','Refinement','Prepress'],['Front cover','Full wrap','Digital cover']],
['Printing & Binding','Reliable production coordination for quality short and large print runs.','We help clients select practical paper, binding and finishing options and prepare files for production.',['Appropriate specifications','Quality checks','Coordinated delivery'],['Specification','Quotation','Proof copy','Production','Delivery'],['Printed books','Production report']],
['Content Development','Research-led writing for organisations, businesses and institutions.','Clear, audience-focused content for profiles, reports, publications, campaigns and knowledge products.',['Strategic messaging','Audience relevance','Editorial consistency'],['Brief','Research','Drafting','Review','Finalisation'],['Final copy','Source file','Content guide']],
['Publishing Consultancy','Practical guidance for authors and organisations making publishing decisions.','A focused advisory service on editorial readiness, production, budgets, ISBN pathways and distribution planning.',['Reduced uncertainty','Better budgeting','Actionable roadmap'],['Discovery','Assessment','Consultation','Roadmap'],['Assessment notes','Publishing roadmap']]];
const insert=db.prepare('INSERT OR IGNORE INTO services(name,slug,summary,description,benefits,process,deliverables,featured,sort_order,seo_title,meta_description) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
services.forEach((s,i)=>insert.run(s[0],slugify(s[0],{lower:true,strict:true}),s[1],s[2],JSON.stringify(s[3]),JSON.stringify(s[4]),JSON.stringify(s[5]),i<6?1:0,i,s[0]+' Kenya | Wise Pen N Paper',s[1]));
const email=process.env.ADMIN_EMAIL||'admin@wisepennpaper.co.ke'; const pass=process.env.ADMIN_PASSWORD||'ChangeMe-Now-2026!';
const existingAdmin=db.prepare('SELECT id,password_hash FROM users WHERE email=?').get(email); let adminState;
if(!existingAdmin){db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Wise Pen Administrator',email,hashPasswordSync(pass),'super_admin'); adminState='created';}
else if(!verifyPasswordSync(pass,existingAdmin.password_hash)){db.prepare('UPDATE users SET password_hash=?,role=? WHERE id=?').run(hashPasswordSync(pass),'super_admin',existingAdmin.id); adminState='password rotated to match ADMIN_PASSWORD';}
else adminState='already present, password unchanged';
[['Publishing Tips','publishing-tips'],['Writing','writing'],['Editing','editing'],['Book Design','book-design'],['Author Advice','author-advice'],['Business Branding','business-branding'],['Content Development','content-development'],['Industry News','industry-news']].forEach(x=>db.prepare('INSERT OR IGNORE INTO categories(name,slug) VALUES(?,?)').run(...x));
const faq=db.prepare('INSERT OR IGNORE INTO faqs(id,question,answer,category,sort_order) VALUES(?,?,?,?,?)');
[['How do I start a publishing project?','Submit the quote form with your project summary and any available manuscript. Our team reviews the materials and responds with recommended next steps.','Getting Started'],['Can I submit an unfinished manuscript?','Yes. We can assess an early draft and recommend content development, co-writing or editorial support before design and production.','Manuscripts'],['Do you work with organisations as well as authors?','Yes. Wise Pen N’ Paper supports authors, businesses, NGOs and institutions with books, reports, magazines, profiles and branded publications.','Services']].forEach((x,i)=>faq.run(i+1,...x,i));
const settings={company_name:'The Wise Pen N’ Paper',tagline:'Turning Ideas Into Books, Brands & Stories That Matter.',email:'info@wisepennpaper.co.ke',phone:'+254 769 1538 21',address:'Nairobi, Kenya',hours:'Monday–Friday, 8:30 AM–5:00 PM',whatsapp:'254769153821'};
for(const [k,v] of Object.entries(settings)) db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v);
console.log(`Seed complete. Admin ${email}: ${adminState}.`);
// The admin account is the highest-value credential here, so say plainly when
// the configured one would be rejected for an ordinary client.
const adminVerdict=assessPassword(pass,{email,name:'Wise Pen Administrator'});
if(!adminVerdict.ok)console.warn(`WARNING: ADMIN_PASSWORD is weak — ${adminVerdict.problem} Client accounts must pass this check (minimum ${MIN_LENGTH} characters); set a stronger ADMIN_PASSWORD and re-run the seed before deploying.`);
console.log('Business statistics are not seeded. Add verified values for books_published, authors_supported, projects_completed, years_experience and organisations_served to the settings table; the homepage statistics band stays hidden until then.');

db.close();
